name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build plugin
        run: dotnet build --configuration Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: DirectShow-Plugin-DLL
          path: bin/Release/**/*.dll
